# .github/workflows/develop.yaml

name: Kubeapp UI Components - Storybook UI Component Run Tests
on:
  pull_request:
    branches:
      - develop
    types: [closed]
  push:
    branches:
      - develop


jobs:
  build:
#    if: github.event.pull_request.merged == true
    name: Kubeapp UI Components - Run Jest tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Source Node.js 16 image
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install node modules
        run: npm ci

      - name: Jest unit testing
        run: npm run test:generate-output
