# .github/workflows/review.yaml

name: Kubeapp UI Components - Storybook UI Component Build and Deployment - REVIEW

on:
  create:
    branches:
      - review
  pull_request:
    branches:
      - review
    types: [closed]
  push:
    branches:
      - review

jobs:
  deploy:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    name: Deploy Storybook to Google App Engine for QA
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Source Node.js 16 image
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install node modules
        run: npm ci

      - name: Jest unit testing
        run: npm run test:generate-output

      - name: Build static storybook content
        run: npm run build-storybook

      - name: Service account authentication to GCP
        id: 'auth'
        uses: 'google-github-actions/auth@v0'
        with:
          credentials_json: '${{ secrets.CSKY_DEVELOPMENT_SA_KEY }}'

      - name: Deploy iposs-appengine to GAE service - REVIEW
        id: 'deploy'
        uses: google-github-actions/deploy-appengine@main
        with:
          deliverables: iposs-appengine-review.yaml

      - name: 'show output'
        run: 'echo ${{ steps.deploy.outputs.url }}'




